name: Calling the Reusable Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: .github/workflows/reusable-workflow.yml
    with:
      environment: dev
    secrets:
      Secret: ${{ secrets.TOKEN }}
