name: Calling the Reusable Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reusable Workflow
        uses: ./.github/workflows/reusable-workflow.yml@main  # Replace 'main' with your branch or tag
        with:
          environment: dev
        secrets:
          Secret: ${{ secrets.TOKEN }}
