name: Calling the Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true

jobs:
  call-reusable-workflow:
        uses: Dinesh-medtech/git-actions-node/.github/workflows/reusable_workflow.yml@main
        with:
          environment: ${{ github.event.inputs.environment }}
          Secret: ${{ secrets.TOKEN }}
