name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev


    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: variable
        run : echo "the value of variable is ${{vars.VAR1}}"
      - name: Secrets
        run : echo "the value of secrets is ${{secrets.TOKEN}}"
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run tests
        if : ${{vars.VAR1}} == '1234'
        run: npm test
