name: Passing Variables Between Jobs

on: 
  push:
    branches: [main]

jobs:
  jobA:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.set_output.outputs.my_var }}
    steps:
      - name: Set output variable
        id: set_output
        run: echo "::set-output name=my_var::Hello, World!"

  jobB:
    needs: jobA
    runs-on: ubuntu-latest
    steps:
      - name: Use the output variable from jobA
        run: echo "The variable from jobA is ${{ needs.jobA.outputs.my_var }}"
