name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        default: 'dev'
        required: true
    secrets:
      Secret:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment
        run: echo "Environment is ${{ inputs.environment }}"

      - name: Secret
        run: echo "The secret is ${{ secrets.Secret }}"
