name: WorkFlow_Dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type : choice
        options:
          - dev
          - production
          - stageing

      notify :
        description : 'notify'
        type : boolean
        required : true
        default : false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display environment
        run: echo "Environment is ${{ github.event.inputs.environment }}"
